name: Secret Scanning

on:
  push:
    branches:
      - DEV
  pull_request:
    branches:
      - DEV

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install GitLeaks (Corrected method to download the release)
      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v7.8.0/gitleaks-linux-amd64-v7.8.0.tar.gz -o gitleaks.tar.gz
          tar -xzvf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin/

      # Step 3: Run GitLeaks to scan for secrets
      - name: Run GitLeaks scan
        run: gitleaks detect --source=. --report=gitleaks-report.json

      # Step 4: Upload GitLeaks report as an artifact
      - name: Upload GitLeaks report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json

      # Optional: Fail the build if secrets are found
      - name: Fail if secrets are found
        run: |
          if grep -q '\"leaks\":' gitleaks-report.json && grep -q '\"line\":' gitleaks-report.json; then
            echo "Leaked secrets found! Please check the gitleaks report." && exit 1;
          fi
