name: Test Simulated API Key Leak Detection

on: 
  push:
    branches:
      - DEV

jobs:
  simulate-api-leak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Simulate API key leak (mock API request)
      run: |
        # Simulate a "leak" by sending a request to a mock API
        curl -sSL "https://mockbin.org/bin/your-generated-bin-id" > response.json
        cat response.json

    - name: Install Gitleaks
      run: |
        # Install Gitleaks for testing secrets in files
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.1.0/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
        sudo chmod +x /usr/local/bin/gitleaks

    - name: Run Gitleaks to detect leaked API key
      run: |
        # Simulate a repository scan for secrets (response.json as a file)
        gitleaks detect --source=.
        
         # Step 4: Check the Gitleaks report and fail if any secrets are found
    - name: Fail if secrets are detected
      run: |
          if [ -s /tmp/gitleaks-report.json ]; then
            echo "Secrets detected in the repository:"
            cat /tmp/gitleaks-report.json
            exit 1
          else
            echo "No secrets found in the repository."
          fi
