name: Test Simulated API Key Leak Detection

on: 
  push:
    branches:
      - DEV

jobs:
  simulate-api-leak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Simulate API key leak (mock API request)
      run: |
        # Simulate a "leak" by sending a request to a mock API
        curl -sSL "https://mockbin.org/bin/your-generated-bin-id" > response.json
        cat response.json

    - name: Install Gitleaks
      run: |
        # Download the correct binary version of Gitleaks (for Linux)
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.1.0/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
        # Check if the file is a valid binary
        file /usr/local/bin/gitleaks
        # Ensure the binary is executable
        sudo chmod +x /usr/local/bin/gitleaks
        # Verify the Gitleaks installation
        gitleaks --version

    - name: Run Gitleaks to detect secrets
      run: |
        # Run Gitleaks to detect secrets and generate a report
        gitleaks detect --source=$GITHUB_WORKSPACE --report=$GITHUB_WORKSPACE/gitleaks-report.json

    - name: Upload Gitleaks report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: gitleaks-report
        path: $GITHUB_WORKSPACE/gitleaks-report.json
