name: Test Simulated API Key Leak Detection

on: 
  push:
    branches:
      - DEV

jobs:
  simulate-api-leak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Simulate API key leak (mock API request)
      run: |
        # Simulate a "leak" by sending a request to a mock API
        curl -sSL "https://mockbin.org/bin/your-generated-bin-id" > response.json
        cat response.json

    - name: Install TruffleHog
      run: |
        # Install TruffleHog for detecting secrets
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install truffleHog

    # Step 3: Run TruffleHog to scan for secrets
    - name: Run TruffleHog scan
      run: |
          trufflehog --json --since_commit HEAD --max_depth 10 https://github.com/${{ github.repository }} > /tmp/trufflehog-report.json
      # Step 4: Check for secrets and fail if any are found
    - name: Fail if secrets are detected
      run: |
          if [ -s /tmp/trufflehog-report.json ]; then
            echo "Secrets detected in the repository:"
            cat /tmp/trufflehog-report.json
            exit 1
          else
            echo "No secrets found in the repository."
          fi
