name: Detect Secrets Leak with TruffleHog
on:
  push:
    branches:
      - DEV
  pull_request:
    branches:
      - DEV
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Install TruffleHog
      - name: Install TruffleHog
        run: |
          curl -sSL https://github.com/dxa4481/truffleHog/releases/download/v2.0.1/trufflehog_2.0.1_linux_x86_64.tar.gz -o trufflehog.tar.gz
          tar -xzf trufflehog.tar.gz
          sudo mv trufflehog /usr/local/bin/
      # Step 3: Run TruffleHog to scan for secrets
      - name: Run TruffleHog scan
        run: |
          trufflehog --json --since_commit HEAD --max_depth 10 https://github.com/${{ github.repository }} > /tmp/trufflehog-report.json
      # Step 4: Check for secrets and fail if any are found
      - name: Fail if secrets are detected
        run: |
          if [ -s /tmp/trufflehog-report.json ]; then
            echo "Secrets detected in the repository:"
            cat /tmp/trufflehog-report.json
            exit 1
          else
            echo "No secrets found in the repository."
          fi
